// The MIT License (MIT)

// Copyright (c) 2023 neil kalman (https://codepen.io/thatkookooguy/pen/VPJpaW)

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import styled, { css, keyframes } from 'styled-components';

export default function Quotes({ quotes, avatars }) {
  return (
    <DivTrain1>
      <DivTrain2>
        <DivTrain3>
          <DivTrain4>
            {quotes?.map((q, index) => (
              <Bubble key={`quote-${index}-${q}`} img={avatars[index % avatars.length]} index={index} className={index % 2 ? 'left' : 'right'}>
                <Avatar src={avatars[index % avatars.length]} index={index} className={index % 2 ? 'left' : 'right'} />
                {q}
              </Bubble>
            ))}
          </DivTrain4>
        </DivTrain3>
      </DivTrain2>
    </DivTrain1>
  );
}

/************************  ANIMATIONS  ************************/
const bubbleAnimation = keyframes`
/* ----------------------------------------------
 * Generated by Animista on 2023-6-5 19:13:39
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bounce-in-fwd
 * ----------------------------------------
 */
  0% {
    transform: scale(0.5);
    filter: blur(4px);
    opacity: 0;
  }
  100% {
    transform: scale(1);
    filter: blur(0px);
    opacity: 1;
  }
`;

const avatarAnimation = keyframes`
  0% { transform: scale3d(1, 1, 1); }
  30% { transform: scale3d(1.25, 0.75, 1); }
  40% { transform: scale3d(0.75, 1.25, 1); }
  50% { transform: scale3d(1.15, 0.85, 1); }
  65% { transform: scale3d(0.95, 1.05, 1); }
  75% { transform: scale3d(1.05, 0.95, 1); }
  100% { transform: scale3d(1, 1, 1); }
`;

/************************  STYLES  ************************/
const DivTrain1 = styled.div`
  padding: 0 0 5em;

  @media (min-width: 992px) {
    padding: 5.5em 0 6.5em;
  }
`;

const DivTrain2 = styled.div`
  box-sizing: border-box;
  margin-left: auto;
  margin-right: auto;
  max-width: 1140px;
  padding-left: 15px;
  padding-right: 15px;
`;

const DivTrain3 = styled.div`
  box-sizing: border-box;
  margin-left: -15px;
  margin-right: -15px;

  &::after {
    clear: both;
    content: '';
    display: table;
  }
`;

const DivTrain4 = styled.div`
  float: left;
  box-sizing: border-box;
  min-height: 1px;
  padding: 0 15px;
  margin: 0;
  width: 100%;

  @media (min-width: 992px) {
    width: 66.66667%;
    padding-left: 15px;
    padding-right: 15px;
    position: relative;
    margin-left: 16.66667%;
  }

  @media (min-width: 992px) {
    p {
      font-size: 20px;
      line-height: 150%;
    }
  }
`;

const Bubble = styled.p`
  position: relative;
  clear: both;
  display: inline-block;
  max-width: 62.5%;
  padding: 14px;
  margin: 0 0 50px 0;
  border-radius: 10px;
  background-color: ${({ theme }) => theme.chatBubble};
  /* font: 12px/16px 'Noto Sans', sans-serif; */
  color: ${({ theme }) => theme.chatFont};
  font-size: 20px;
  line-height: 150%;
  word-wrap: break-word;
  ${(props) => css`
    animation: ${bubbleAnimation} 1.1s ${props.index * 0.25}s both;
  `}

  &:after {
    position: absolute;
    content: '';
    top: 10px;
    width: 0;
    height: 0;
    border-top: 10px solid ${({ theme }) => theme.chatBubble};
  }

  &.right {
    float: right;
    margin-right: 65px;

    &:after {
      border-right: 10px solid transparent;
      right: -10px;
    }

    img {
      right: -65px;
    }
  }

  &.left {
    float: left;
    margin-left: 65px;

    &:after {
      border-left: 10px solid transparent;
      left: -10px;
    }

    img {
      left: -65px;
    }
  }

  @media (min-width: 425px) {
    max-width: 67.5%;
  }
  @media (min-width: 768px) {
    max-width: 60%;
  }
  @media (min-width: 992px) {
    max-width: 50%;
  }
`;

const Avatar = styled.img`
  position: absolute;
  top: -10px;
  width: 50px;
  height: 50px;
  border-radius: 50%;

  &:hover {
    cursor: grab;
    animation: ${avatarAnimation} 0.9s both;
  }
`;
